# Define the system of units to use internally. 
InternalUnitSystem:
  UnitMass_in_cgs:     1.98841e43    # 10^10 M_sun
  UnitLength_in_cgs:   3.08567758e24 # 1 Mpc
  UnitVelocity_in_cgs: 1e5           # 1 km/s
  UnitCurrent_in_cgs:  1             # Amperes
  UnitTemp_in_cgs:     1             # Kelvin

# Planck-13 cosmology
Cosmology:
  h:              $HubbleParam      # Reduced Hubble constant
  a_begin:        $starting_a       # Initial scale-factor of the simulation
  a_end:          $finishing_a      # Final scale factor of the simulation
  Omega_cdm:      $OmegaCDM         # Cold Dark Matter density parameter
  Omega_lambda:   $OmegaLambda      # Dark-energy density parameter
  Omega_b:        $OmegaBaryon      # Baryon density parameter
  
# Parameters governing the time integration
TimeIntegration:
  dt_min:     1e-6 
  dt_max:     1e-2

Scheduler:
  max_top_level_cells: 32
  cell_split_size:     200

# Parameters governing the snapshots
Snapshots:
  basename:            snap
  delta_time:          1.02
  scale_factor_first:  0.02
  output_list_on:      $swift_has_snap_times
  output_list:         snapshot_times.txt
  subdir:              snapshots 
  select_output_on:    $swift_has_select_output
  select_output:       select_output.yml

# Parameters governing the conserved quantities statistics
Statistics:
  delta_time:          1.02
  scale_factor_first:  0.02
 
# Restart files.
Restarts:
  enable:             1
  save:               1          # Keep copies
  onexit:             1
  subdir:             restart    # Sub-directory of the directory where SWIFT is run
  basename:           swift
  delta_hours:        4.0
  stop_steps:         100
  max_run_time:       71.5       # In hours
  resubmit_on_exit:   1
  resubmit_command:   ./auto_resubmit

# Parameters for the self-gravity scheme
Gravity:
  eta:                              0.025         
  comoving_DM_softening:            $eps_dm
  softening_ratio_background:       $softening_ratio_background
  max_physical_DM_softening:        $eps_dm_physical
  mesh_side_length:                 512
  MAC:                              adaptive
  theta_cr:                         0.7
  epsilon_fmm:                      0.001

# Parameters related to the initial conditions
InitialConditions:
  file_name:                   ics.hdf5
  periodic:                    1
  cleanup_h_factors:           1    
  cleanup_velocity_factors:    1  
